---
title: "NotasR"
author: "AVallarino"
date: "27/8/2017"
output: html_document
---

---  

**Verificar instalación de paquete**  
Valida si un paquete se encuentra instalado. Si no lo está, lo instala.  
```{r}
if(!require(dplyr, quietly = TRUE, warn.conflicts = FALSE) ){
    install.packages('dplyr',
	    dependencies = TRUE, 
	    repos = "http://cran.us.r-project.org")
}

library(tidyverse)
```

---  

**Caputrar excepxión al leer un archivo:**  
Lee un archivo en el directorio de trabajo. Si el archivo no existe, lo descarga al directorio y lo abre.  
```{r}
# Armo array con nombres:
c_names <- c("CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV")

# Cargo archivo de datos y agrego nommbres de columnas:
dat_housing <- try(read.table("housing.dat", header = FALSE, col.names = c_names))

if (inherits(dat_housing, "try-error")) {
  # Descargo datos en directorio de trabajo - Indico nombre destino:
  download.file(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data",
    "housing.dat")
  dat_housing <- read.table("housing.dat", header = FALSE, col.names = c_names)
} 

head(dat_housing)
```

---  

**Descargo .ZIP y lo descomprimo**  
```{r}
# URL con .zip
url <- "https://www.dropbox.com/s/7q8ohggjm8bw5m2/02-tarea.zip?dl=1"

# Defino directorios temporales:
temp <- tempfile()
temp2 <- tempfile()

# Obtengo archivo .zip y lo descomprimo:
download.file(url, temp)
unzip(zipfile = temp, exdir = temp2)

# Obtengo listado de archivos:
temp3 <- paste(temp2, "/02-tarea", sep = "")
csv_list <- list.files(temp3, pattern = "*.csv")

print("- Lista de archivos .CSV:")
csv_list
```

**Cargo listado de archivos del directorio descomprimido**
```{r}
# Obtengo listado de archivos (nombre completo)
paths <- dir(temp3, pattern = "\\.csv$", full.names = TRUE) 
paths <- set_names(paths, basename(paths))

# Cargo los datos de todos los .csv en un solo DataFrame:
data_200x_orig <- map_df(paths, ~read_csv(., col_types = cols(
  edo = col_character(),
  trans_Total = col_double(),
  trans_Mujeres = col_double(),
  trans_Hombres = col_double(),
  noTrans_Total = col_double(),
  noTrans_Mujeres = col_double(),
  noTrans_Hombres = col_double(),
  lesiones_Total = col_double(),
  lesiones_Mujeres = col_double(),
  lesiones_Hombres = col_double())), .id = "filename")

head(data_200x_orig)
```


---  
